version: '3.7'

services:
  api:
    build:
      context: ./api
    depends_on:
      - db
    environment:
      - FLASK_APP=recipes_api:app
    ports:
      - 5000:5000
  db:
    build:
      context: ./db
    user: 1000:1000
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - ./db/.dev-data:/var/lib/postgresql/data
