version: '3.7'

services:
  api:
    build:
      context: ./api
    environment:
      - FLASK_APP=recipes_api:create_app
      - FLASK_ENV=development
      - SQLALCHEMY_DATABASE_URI=postgres://dev:dev@db/dev
    ports:
      - 5000:5000
    volumes:
      - ./api:/opt/api
  db:
    build:
      context: ./db
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
