version: '3.7'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    user: '1000:1000'
    volumes:
      - ./data:/var/lib/postgresql/data
