name: Deploy

on:
  push:
    branches: master

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '13.x'
    - run: npm ci
    - run: env
    - run: git config user.name "Action ${{ github.workflow }}"
    - run: git config user.email "${{ github.actor }}@users.noreply.github.com"
    - run: npm run deploy -- --repo https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
